import type { AuditLogEntry, Client, Profile } from "./types";

// Date demonstrative — folosite doar când nu există o conexiune Supabase
// configurată (vezi src/lib/data/*). Odată setate variabilele de mediu
// NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY, aplicația
// citește automat din baza de date reală, nu din acest fișier.

export const SEED_PROFILES: Profile[] = [
  {
    id: "admin-1",
    role: "admin",
    fullName: "Admin Fitness Club",
    email: "fitnessclub@admin.com",
    phone: null,
    avatarUrl: null,
    birthDate: null,
    yearsExperience: null,
    specializations: [],
    bio: null,
    isActive: true,
    createdAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "trainer-maria",
    role: "trainer",
    fullName: "Maria Ionescu",
    email: "maria.ionescu@example.com",
    phone: null,
    avatarUrl: null,
    birthDate: null,
    yearsExperience: 5,
    specializations: ["Slăbire / definiție", "Nutriție", "Postură / core"],
    bio: "Antrenor specializat pe recompoziție corporală și obiceiuri alimentare sustenabile.",
    isActive: true,
    createdAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "trainer-razvan",
    role: "trainer",
    fullName: "Răzvan Dumitrescu",
    email: "razvan.dumitrescu@example.com",
    phone: null,
    avatarUrl: null,
    birthDate: null,
    yearsExperience: 8,
    specializations: ["Hipertrofie", "Powerlifting", "Forță"],
    bio: "Fost powerlifter, axat pe forță și hipertrofie pentru clienți intermediari/avansați.",
    isActive: true,
    createdAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "trainer-andrei",
    role: "trainer",
    fullName: "Andrei Popescu",
    email: "andrei.popescu@example.com",
    phone: null,
    avatarUrl: null,
    birthDate: null,
    yearsExperience: 3,
    specializations: ["Fitness general", "Mobilitate", "Cardio"],
    bio: null,
    isActive: true,
    createdAt: "2026-05-01T00:00:00Z",
  },
];

function m(
  clientId: string,
  monthsAgo: number,
  weightKg: number,
  heightCm: number,
  extra?: Partial<Client["measurements"][number]>,
) {
  const d = new Date();
  d.setMonth(d.getMonth() - monthsAgo);
  return {
    id: `${clientId}-m${monthsAgo}`,
    clientId,
    recordedAt: d.toISOString(),
    isInitial: monthsAgo === 4,
    weightKg,
    heightCm,
    arms: extra?.arms ?? null,
    chest: extra?.chest ?? null,
    waist: extra?.waist ?? null,
    hips: extra?.hips ?? null,
    thigh: extra?.thigh ?? null,
    calf: extra?.calf ?? null,
    notes: extra?.notes ?? null,
  };
}

export const SEED_CLIENTS: Client[] = [
  {
    id: "client-elena",
    trainerId: "trainer-andrei",
    fullName: "Elena Stoica",
    email: "elena.stoica@example.com",
    phone: "0722 111 222",
    birthDate: "1991-03-12",
    gender: "F",
    status: "activ",
    goals: "Slăbire 8-10 kg și tonifiere generală până la vară.",
    notes: "Progres constant, foarte disciplinată cu dieta.",
    createdAt: "2026-04-20T00:00:00Z",
    anamnesis: {
      medicalConditions: null,
      medications: null,
      injuries: "Ușoare dureri lombare istorice — evită deadlift greu.",
      allergies: null,
      contraindications: null,
      notes: null,
    },
    measurements: [
      m("client-elena", 4, 78, 165, { waist: 88, hips: 104, arms: 30, chest: 96 }),
      m("client-elena", 3, 76, 165, { waist: 86, hips: 102, arms: 30, chest: 95 }),
      m("client-elena", 2, 74, 165, { waist: 84, hips: 100, arms: 29, chest: 94 }),
      m("client-elena", 1, 72, 165, { waist: 82, hips: 98, arms: 29, chest: 93 }),
      m("client-elena", 0, 71, 165, { waist: 80, hips: 97, arms: 28, chest: 92 }),
    ],
    photos: [],
  },
  {
    id: "client-ana",
    trainerId: "trainer-maria",
    fullName: "Ana Constantin",
    email: "ana.constantin@example.com",
    phone: "0733 222 333",
    birthDate: "1990-07-02",
    gender: "F",
    status: "suspendat",
    goals: "Definire abdominală, menținere greutate.",
    notes: "Suspendată temporar — călătorie de lucru 2 luni.",
    createdAt: "2026-04-18T00:00:00Z",
    anamnesis: {
      medicalConditions: null,
      medications: null,
      injuries: null,
      allergies: "Lactoza",
      contraindications: null,
      notes: null,
    },
    measurements: [
      m("client-ana", 4, 68, 170, { waist: 76, hips: 98, arms: 27, chest: 90 }),
      m("client-ana", 3, 67, 170, { waist: 75, hips: 97, arms: 27, chest: 89 }),
      m("client-ana", 2, 65, 170, { waist: 73, hips: 96, arms: 26, chest: 88 }),
      m("client-ana", 1, 62, 170, { waist: 71, hips: 94, arms: 26, chest: 87 }),
      m("client-ana", 0, 61, 170, { waist: 70, hips: 93, arms: 26, chest: 87 }),
    ],
    photos: [],
  },
  {
    id: "client-vlad",
    trainerId: "trainer-maria",
    fullName: "Vlad Pop",
    email: "vlad.pop@example.com",
    phone: "0744 333 444",
    birthDate: "1990-01-20",
    gender: "M",
    status: "activ",
    goals: "Creștere masă musculară, +4 kg masă slabă.",
    notes: null,
    createdAt: "2026-04-15T00:00:00Z",
    anamnesis: {
      medicalConditions: null,
      medications: null,
      injuries: null,
      allergies: null,
      contraindications: null,
      notes: null,
    },
    measurements: [
      m("client-vlad", 4, 74, 175, { arms: 33, chest: 98, waist: 82 }),
      m("client-vlad", 3, 75, 175, { arms: 33.5, chest: 99, waist: 82 }),
      m("client-vlad", 2, 76, 175, { arms: 34, chest: 100, waist: 82 }),
      m("client-vlad", 1, 77, 175, { arms: 34.5, chest: 101, waist: 83 }),
      m("client-vlad", 0, 78, 175, { arms: 35, chest: 102, waist: 83 }),
    ],
    photos: [],
  },
  {
    id: "client-cristina",
    trainerId: "trainer-maria",
    fullName: "Cristina Dima",
    email: "cristina.dima@example.com",
    phone: "0755 444 555",
    birthDate: "1990-11-05",
    gender: "F",
    status: "activ",
    goals: "Recompoziție corporală generală.",
    notes: null,
    createdAt: "2026-04-10T00:00:00Z",
    anamnesis: {
      medicalConditions: null,
      medications: null,
      injuries: null,
      allergies: null,
      contraindications: null,
      notes: null,
    },
    measurements: [
      m("client-cristina", 4, 70, 162, { waist: 78, hips: 100, arms: 27 }),
      m("client-cristina", 3, 69, 162, { waist: 77, hips: 99, arms: 27 }),
      m("client-cristina", 2, 68, 162, { waist: 75, hips: 98, arms: 26 }),
      m("client-cristina", 1, 67, 162, { waist: 74, hips: 97, arms: 26 }),
      m("client-cristina", 0, 66, 162, { waist: 73, hips: 96, arms: 26 }),
    ],
    photos: [],
  },
  {
    id: "client-george",
    trainerId: "trainer-razvan",
    fullName: "George Muntean",
    email: "george.muntean@example.com",
    phone: "0766 555 666",
    birthDate: "1990-02-18",
    gender: "M",
    status: "activ",
    goals: "Slăbire 10 kg, îmbunătățire condiție cardio.",
    notes: null,
    createdAt: "2026-04-05T00:00:00Z",
    anamnesis: {
      medicalConditions: "Tensiune arterială ușor crescută — monitorizare.",
      medications: null,
      injuries: null,
      allergies: null,
      contraindications: "Evită efort cardio maximal fără încălzire.",
      notes: null,
    },
    measurements: [
      m("client-george", 4, 95, 180, { waist: 104, chest: 108 }),
      m("client-george", 3, 93, 180, { waist: 101, chest: 107 }),
      m("client-george", 2, 91, 180, { waist: 98, chest: 106 }),
      m("client-george", 1, 89, 180, { waist: 96, chest: 105 }),
      m("client-george", 0, 88, 180, { waist: 94, chest: 104 }),
    ],
    photos: [],
  },
  {
    id: "client-andreea",
    trainerId: "trainer-razvan",
    fullName: "Andreea Marin",
    email: "andreea.marin@example.com",
    phone: "0777 666 777",
    birthDate: "1990-09-09",
    gender: "F",
    status: "activ",
    goals: "Tonifiere generală, pregătire eveniment.",
    notes: null,
    createdAt: "2026-04-02T00:00:00Z",
    anamnesis: {
      medicalConditions: null,
      medications: null,
      injuries: null,
      allergies: null,
      contraindications: null,
      notes: null,
    },
    measurements: [
      m("client-andreea", 4, 82, 168, { waist: 88, hips: 106 }),
      m("client-andreea", 3, 80, 168, { waist: 86, hips: 104 }),
      m("client-andreea", 2, 78, 168, { waist: 84, hips: 102 }),
      m("client-andreea", 1, 77, 168, { waist: 83, hips: 101 }),
      m("client-andreea", 0, 76, 168, { waist: 82, hips: 100 }),
    ],
    photos: [],
  },
  {
    id: "client-tudor",
    trainerId: "trainer-razvan",
    fullName: "Tudor Avram",
    email: "tudor.avram@example.com",
    phone: "0788 777 888",
    birthDate: "1991-04-25",
    gender: "M",
    status: "activ",
    goals: "Slăbire semnificativă — start 110 kg.",
    notes: "Cea mai bună evoluție din platformă până acum.",
    createdAt: "2026-03-25T00:00:00Z",
    anamnesis: {
      medicalConditions: null,
      medications: null,
      injuries: "Genunchi drept — sensibil la genuflexiuni adânci.",
      allergies: null,
      contraindications: null,
      notes: null,
    },
    measurements: [
      m("client-tudor", 4, 110, 185, { waist: 118, chest: 112 }),
      m("client-tudor", 3, 104, 185, { waist: 112, chest: 110 }),
      m("client-tudor", 2, 98, 185, { waist: 105, chest: 108 }),
      m("client-tudor", 1, 92, 185, { waist: 99, chest: 106 }),
      m("client-tudor", 0, 89, 185, { waist: 95, chest: 104 }),
    ],
    photos: [],
  },
];

export const SEED_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: "log-1",
    actorId: "admin-1",
    actorName: "Admin Fitness Club",
    action: "stergere",
    entityType: "client",
    entityLabel: "Mihai Radu",
    summary: "Ștergere client: Mihai Radu",
    createdAt: "2026-08-06T10:00:00Z",
  },
  {
    id: "log-2",
    actorId: "trainer-maria",
    actorName: "Maria Ionescu",
    action: "modificare",
    entityType: "masuratoare",
    entityLabel: "Vlad Pop",
    summary: "Actualizare lunară adăugată",
    createdAt: "2026-08-05T17:20:00Z",
  },
  {
    id: "log-3",
    actorId: "trainer-razvan",
    actorName: "Răzvan Dumitrescu",
    action: "creare",
    entityType: "client",
    entityLabel: "Tudor Avram",
    summary: "Creare client: Tudor Avram",
    createdAt: "2026-08-04T11:05:00Z",
  },
  {
    id: "log-4",
    actorId: "admin-1",
    actorName: "Admin Fitness Club",
    action: "creare",
    entityType: "utilizator",
    entityLabel: "Andrei Popescu",
    summary: "Creare cont antrenor: Andrei Popescu",
    createdAt: "2026-08-02T09:40:00Z",
  },
];
